name: Server CI
on:
  push:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install NPM dependencies
        working-directory: ./wispe-server
        run: npm install

      - name: Setup Test Environment Database
        uses: SpicyPizza/create-envfile@v2.0
        with:
          directory: ./wispe-server
          envkey_NODE_ENV: TEST
          file_name: test.env
          envkey_POSTGRES_USERNAME: ${{ secrets.TEST_DATABASE_USERNAME }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
          envkey_POSTGRES_HOST: ${{ secrets.TEST_DATABASE_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.TEST_DATABASE_PORT }}
          envkey_POSTGRES_DATABASE: ${{ secrets.TEST_DATABASE_NAME }}
          envkey_API_PORT: ${{ secrets.TEST_SERVER_API_PORT }}
          envkey_JWT_SECRET: ${{ secrets.TEST_SERVER_JWT_SECRET }}
          envkey_AUTH_PASSWORD_HASH_ROUNDS: 1
          envkey_AUTH_JWT_SECRET: ${{ secrets.TEST_AUTH_JWT_SECRET }}
          envkey_WEATHER_WEATHERAPI_API_KEY: ${{ secrets.TEST_WEATHER_WEATHERAPI_API_KEY }}
          envkey_WEATHER_WEATHERAPI_CITY: ${{ secrets.TEST_WEATHER_WEATHERAPI_CITY }}

      - name: Run Tests
        working-directory: ./wispe-server
        run: npm run test